services:
  - type: worker
    name: mining-alert-bot
    env: python
    runtime: python-3.10
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        fromDotEnv: true
      - key: CHAT_ID
        fromDotEnv: true
